# -*- coding: utf-8 -*-
"""generate_test_csv.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZ7WzYRlTczMxLJKuNFWN3mx8MipUs6I
"""

import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Define dataset parameters
n_rows = 300
products = [f"prod_{i}" for i in range(1, 11)]  # 10 unique products
categories = ["electronics", "furniture", "health", "computers", "watches"]

# Generate random dates in DD-MM-YYYY format
dates = pd.date_range(start="2017-01-01", periods=30, freq="MS").strftime("%d-%m-%Y").tolist()

# Build the raw dataframe
df = pd.DataFrame({
    "product_id": np.random.choice(products, n_rows),
    "product_category_name": np.random.choice(categories, n_rows),
    "month_year": np.random.choice(dates, n_rows),
    "qty": np.random.randint(1, 80, n_rows),
    "unit_price": np.random.uniform(20.0, 250.0, n_rows).round(2),
    "freight_price": np.random.uniform(5.0, 25.0, n_rows).round(2),
    "product_score": np.random.uniform(3.0, 5.0, n_rows).round(1),
    "customers": np.random.randint(10, 150, n_rows),
    "weekend": np.random.randint(0, 8, n_rows),
    "holiday": np.random.choice([0, 1], n_rows, p=[0.8, 0.2]),
    "s": np.random.uniform(1.0, 25.0, n_rows).round(2), # Seasonality index
    "lag_price": np.random.uniform(20.0, 250.0, n_rows).round(2),
})

# Generate competitor prices clustered around the unit price
df["comp_1"] = (df["unit_price"] * np.random.uniform(0.9, 1.1, n_rows)).round(2)
df["comp_2"] = (df["unit_price"] * np.random.uniform(0.85, 1.15, n_rows)).round(2)
df["comp_3"] = (df["unit_price"] * np.random.uniform(0.95, 1.05, n_rows)).round(2)

# Sort logically by product and date
df["temp_date"] = pd.to_datetime(df["month_year"], format="%d-%m-%Y")
df = df.sort_values(["product_id", "temp_date"]).drop(columns=["temp_date"])

# Export to CSV
file_name = "Retail_Price_Optimization_Test.csv"
df.to_csv(file_name, index=False)

print(f"✅ Successfully generated {file_name} with {len(df)} rows!")